functional: 
- Пользователь должен иметь возможность искать товары по ключевому слову или категории
- Пользователь должен иметь возможность фильтровать товары
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины

non-functional:
- Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт нужно протестировать на совместимость с последними версиями браузеров
- Важно, чтобы сайт мог обрабатывать большое количество трафика
- Сайт должен быть доступен на различных устройствах
- Сайт должен иметь мобильную версию

implicit: 
- В каталоге товаров отображать добавленные в корзину
- Отображать количество выбранных товаров на карточке в каталоге
- Добать кнопке "В корзину" функционал выбора количества товара, не переходя в корзину
- При выборе категории, фильтр по производителям должен динамически изменять доступные параметры  для выбора
- Отображать кнопку "Следующая" только при условии превышения количества товара отображаемого на одной странице
- Отображать в каталоге товаров номер текущей страницы с возможностью переходов "вперед" и "назад"
